version: '3.9'
services:
  hyperf-poc:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hyperf-poc
    platform: linux/amd64
    volumes:
      - ./:/app
    ports:
      - 9501:9501
